# Generated by Django 4.0.6 on 2022-07-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_main', '0002_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
